// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bookstore/v1/bookstore.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/ductone/protoc-gen-mcpgw/mcpgw/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author_Gender int32

const (
	Author_GENDER_UNSPECIFIED Author_Gender = 0
	Author_GENDER_MALE        Author_Gender = 1
	Author_GENDER_FEMALE      Author_Gender = 2
)

// Enum value maps for Author_Gender.
var (
	Author_Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Author_Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Author_Gender) Enum() *Author_Gender {
	p := new(Author_Gender)
	*p = x
	return p
}

func (x Author_Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Author_Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_bookstore_v1_bookstore_proto_enumTypes[0].Descriptor()
}

func (Author_Gender) Type() protoreflect.EnumType {
	return &file_bookstore_v1_bookstore_proto_enumTypes[0]
}

func (x Author_Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CreateGenreRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateGenreRequest) Reset() {
	*x = CreateGenreRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenreRequest) ProtoMessage() {}

func (x *CreateGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateGenreRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *CreateGenreRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CreateGenreRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateGenreRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type CreateGenreRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 CreateGenreRequest_builder) Build() *CreateGenreRequest {
	m0 := &CreateGenreRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type CreateGenreResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Genre *Genre                 `protobuf:"bytes,1,opt,name=genre"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateGenreResponse) Reset() {
	*x = CreateGenreResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenreResponse) ProtoMessage() {}

func (x *CreateGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateGenreResponse) GetGenre() *Genre {
	if x != nil {
		return x.xxx_hidden_Genre
	}
	return nil
}

func (x *CreateGenreResponse) SetGenre(v *Genre) {
	x.xxx_hidden_Genre = v
}

func (x *CreateGenreResponse) HasGenre() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Genre != nil
}

func (x *CreateGenreResponse) ClearGenre() {
	x.xxx_hidden_Genre = nil
}

type CreateGenreResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Genre *Genre
}

func (b0 CreateGenreResponse_builder) Build() *CreateGenreResponse {
	m0 := &CreateGenreResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Genre = b.Genre
	return m0
}

type GetGenreRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GenreId     *string                `protobuf:"bytes,1,opt,name=genre_id,json=genreId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetGenreRequest) Reset() {
	*x = GetGenreRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenreRequest) ProtoMessage() {}

func (x *GetGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetGenreRequest) GetGenreId() string {
	if x != nil {
		if x.xxx_hidden_GenreId != nil {
			return *x.xxx_hidden_GenreId
		}
		return ""
	}
	return ""
}

func (x *GetGenreRequest) SetGenreId(v string) {
	x.xxx_hidden_GenreId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetGenreRequest) HasGenreId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetGenreRequest) ClearGenreId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_GenreId = nil
}

type GetGenreRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GenreId *string
}

func (b0 GetGenreRequest_builder) Build() *GetGenreRequest {
	m0 := &GetGenreRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GenreId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_GenreId = b.GenreId
	}
	return m0
}

type GetGenreResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Genre *Genre                 `protobuf:"bytes,1,opt,name=genre"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetGenreResponse) Reset() {
	*x = GetGenreResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenreResponse) ProtoMessage() {}

func (x *GetGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetGenreResponse) GetGenre() *Genre {
	if x != nil {
		return x.xxx_hidden_Genre
	}
	return nil
}

func (x *GetGenreResponse) SetGenre(v *Genre) {
	x.xxx_hidden_Genre = v
}

func (x *GetGenreResponse) HasGenre() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Genre != nil
}

func (x *GetGenreResponse) ClearGenre() {
	x.xxx_hidden_Genre = nil
}

type GetGenreResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Genre *Genre
}

func (b0 GetGenreResponse_builder) Build() *GetGenreResponse {
	m0 := &GetGenreResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Genre = b.Genre
	return m0
}

type DeleteGenreRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GenreId     *string                `protobuf:"bytes,1,opt,name=genre_id,json=genreId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteGenreRequest) Reset() {
	*x = DeleteGenreRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenreRequest) ProtoMessage() {}

func (x *DeleteGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteGenreRequest) GetGenreId() string {
	if x != nil {
		if x.xxx_hidden_GenreId != nil {
			return *x.xxx_hidden_GenreId
		}
		return ""
	}
	return ""
}

func (x *DeleteGenreRequest) SetGenreId(v string) {
	x.xxx_hidden_GenreId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteGenreRequest) HasGenreId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteGenreRequest) ClearGenreId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_GenreId = nil
}

type DeleteGenreRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GenreId *string
}

func (b0 DeleteGenreRequest_builder) Build() *DeleteGenreRequest {
	m0 := &DeleteGenreRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GenreId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_GenreId = b.GenreId
	}
	return m0
}

type DeleteGenreResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGenreResponse) Reset() {
	*x = DeleteGenreResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenreResponse) ProtoMessage() {}

func (x *DeleteGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteGenreResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteGenreResponse_builder) Build() *DeleteGenreResponse {
	m0 := &DeleteGenreResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListGenresRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGenresRequest) Reset() {
	*x = ListGenresRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGenresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGenresRequest) ProtoMessage() {}

func (x *ListGenresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListGenresRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListGenresRequest_builder) Build() *ListGenresRequest {
	m0 := &ListGenresRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListGenresResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Genres *[]*Genre              `protobuf:"bytes,1,rep,name=genres"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListGenresResponse) Reset() {
	*x = ListGenresResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGenresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGenresResponse) ProtoMessage() {}

func (x *ListGenresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListGenresResponse) GetGenres() []*Genre {
	if x != nil {
		if x.xxx_hidden_Genres != nil {
			return *x.xxx_hidden_Genres
		}
	}
	return nil
}

func (x *ListGenresResponse) SetGenres(v []*Genre) {
	x.xxx_hidden_Genres = &v
}

type ListGenresResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Genres []*Genre
}

func (b0 ListGenresResponse_builder) Build() *ListGenresResponse {
	m0 := &ListGenresResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Genres = &b.Genres
	return m0
}

type DeleteShelfResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShelfResponse) Reset() {
	*x = DeleteShelfResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShelfResponse) ProtoMessage() {}

func (x *DeleteShelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteShelfResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteShelfResponse_builder) Build() *DeleteShelfResponse {
	m0 := &DeleteShelfResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListShelvesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShelvesRequest) Reset() {
	*x = ListShelvesRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShelvesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShelvesRequest) ProtoMessage() {}

func (x *ListShelvesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListShelvesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListShelvesRequest_builder) Build() *ListShelvesRequest {
	m0 := &ListShelvesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DeleteBookResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteBookResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteBookResponse_builder) Build() *DeleteBookResponse {
	m0 := &DeleteBookResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CreateShelfResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Shelf *Shelf                 `protobuf:"bytes,1,opt,name=shelf"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateShelfResponse) Reset() {
	*x = CreateShelfResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfResponse) ProtoMessage() {}

func (x *CreateShelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateShelfResponse) GetShelf() *Shelf {
	if x != nil {
		return x.xxx_hidden_Shelf
	}
	return nil
}

func (x *CreateShelfResponse) SetShelf(v *Shelf) {
	x.xxx_hidden_Shelf = v
}

func (x *CreateShelfResponse) HasShelf() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Shelf != nil
}

func (x *CreateShelfResponse) ClearShelf() {
	x.xxx_hidden_Shelf = nil
}

type CreateShelfResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Shelf *Shelf
}

func (b0 CreateShelfResponse_builder) Build() *CreateShelfResponse {
	m0 := &CreateShelfResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Shelf = b.Shelf
	return m0
}

type CreateBookResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Book *Book                  `protobuf:"bytes,1,opt,name=book"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBookResponse) Reset() {
	*x = CreateBookResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookResponse) ProtoMessage() {}

func (x *CreateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateBookResponse) GetBook() *Book {
	if x != nil {
		return x.xxx_hidden_Book
	}
	return nil
}

func (x *CreateBookResponse) SetBook(v *Book) {
	x.xxx_hidden_Book = v
}

func (x *CreateBookResponse) HasBook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Book != nil
}

func (x *CreateBookResponse) ClearBook() {
	x.xxx_hidden_Book = nil
}

type CreateBookResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Book *Book
}

func (b0 CreateBookResponse_builder) Build() *CreateBookResponse {
	m0 := &CreateBookResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Book = b.Book
	return m0
}

type GetBookResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Book *Book                  `protobuf:"bytes,1,opt,name=book"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBookResponse) GetBook() *Book {
	if x != nil {
		return x.xxx_hidden_Book
	}
	return nil
}

func (x *GetBookResponse) SetBook(v *Book) {
	x.xxx_hidden_Book = v
}

func (x *GetBookResponse) HasBook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Book != nil
}

func (x *GetBookResponse) ClearBook() {
	x.xxx_hidden_Book = nil
}

type GetBookResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Book *Book
}

func (b0 GetBookResponse_builder) Build() *GetBookResponse {
	m0 := &GetBookResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Book = b.Book
	return m0
}

type UpdateBookResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Book *Book                  `protobuf:"bytes,1,opt,name=book"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateBookResponse) Reset() {
	*x = UpdateBookResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookResponse) ProtoMessage() {}

func (x *UpdateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateBookResponse) GetBook() *Book {
	if x != nil {
		return x.xxx_hidden_Book
	}
	return nil
}

func (x *UpdateBookResponse) SetBook(v *Book) {
	x.xxx_hidden_Book = v
}

func (x *UpdateBookResponse) HasBook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Book != nil
}

func (x *UpdateBookResponse) ClearBook() {
	x.xxx_hidden_Book = nil
}

type UpdateBookResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Book *Book
}

func (b0 UpdateBookResponse_builder) Build() *UpdateBookResponse {
	m0 := &UpdateBookResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Book = b.Book
	return m0
}

type GetAuthorResponse struct {
	state             protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Author *Author                   `protobuf:"bytes,1,opt,name=author"`
	xxx_hidden_Genre  isGetAuthorResponse_Genre `protobuf_oneof:"genre"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAuthorResponse) Reset() {
	*x = GetAuthorResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorResponse) ProtoMessage() {}

func (x *GetAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.xxx_hidden_Author
	}
	return nil
}

func (x *GetAuthorResponse) GetFiction() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Genre.(*getAuthorResponse_Fiction); ok {
			return x.Fiction
		}
	}
	return false
}

func (x *GetAuthorResponse) GetNonfiction() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Genre.(*getAuthorResponse_Nonfiction); ok {
			return x.Nonfiction
		}
	}
	return false
}

func (x *GetAuthorResponse) SetAuthor(v *Author) {
	x.xxx_hidden_Author = v
}

func (x *GetAuthorResponse) SetFiction(v bool) {
	x.xxx_hidden_Genre = &getAuthorResponse_Fiction{v}
}

func (x *GetAuthorResponse) SetNonfiction(v bool) {
	x.xxx_hidden_Genre = &getAuthorResponse_Nonfiction{v}
}

func (x *GetAuthorResponse) HasAuthor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Author != nil
}

func (x *GetAuthorResponse) HasGenre() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Genre != nil
}

func (x *GetAuthorResponse) HasFiction() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Genre.(*getAuthorResponse_Fiction)
	return ok
}

func (x *GetAuthorResponse) HasNonfiction() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Genre.(*getAuthorResponse_Nonfiction)
	return ok
}

func (x *GetAuthorResponse) ClearAuthor() {
	x.xxx_hidden_Author = nil
}

func (x *GetAuthorResponse) ClearGenre() {
	x.xxx_hidden_Genre = nil
}

func (x *GetAuthorResponse) ClearFiction() {
	if _, ok := x.xxx_hidden_Genre.(*getAuthorResponse_Fiction); ok {
		x.xxx_hidden_Genre = nil
	}
}

func (x *GetAuthorResponse) ClearNonfiction() {
	if _, ok := x.xxx_hidden_Genre.(*getAuthorResponse_Nonfiction); ok {
		x.xxx_hidden_Genre = nil
	}
}

const GetAuthorResponse_Genre_not_set_case case_GetAuthorResponse_Genre = 0
const GetAuthorResponse_Fiction_case case_GetAuthorResponse_Genre = 2
const GetAuthorResponse_Nonfiction_case case_GetAuthorResponse_Genre = 3

func (x *GetAuthorResponse) WhichGenre() case_GetAuthorResponse_Genre {
	if x == nil {
		return GetAuthorResponse_Genre_not_set_case
	}
	switch x.xxx_hidden_Genre.(type) {
	case *getAuthorResponse_Fiction:
		return GetAuthorResponse_Fiction_case
	case *getAuthorResponse_Nonfiction:
		return GetAuthorResponse_Nonfiction_case
	default:
		return GetAuthorResponse_Genre_not_set_case
	}
}

type GetAuthorResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Author *Author
	// Fields of oneof xxx_hidden_Genre:
	Fiction    *bool
	Nonfiction *bool
	// -- end of xxx_hidden_Genre
}

func (b0 GetAuthorResponse_builder) Build() *GetAuthorResponse {
	m0 := &GetAuthorResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Author = b.Author
	if b.Fiction != nil {
		x.xxx_hidden_Genre = &getAuthorResponse_Fiction{*b.Fiction}
	}
	if b.Nonfiction != nil {
		x.xxx_hidden_Genre = &getAuthorResponse_Nonfiction{*b.Nonfiction}
	}
	return m0
}

type case_GetAuthorResponse_Genre protoreflect.FieldNumber

func (x case_GetAuthorResponse_Genre) String() string {
	md := file_bookstore_v1_bookstore_proto_msgTypes[15].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isGetAuthorResponse_Genre interface {
	isGetAuthorResponse_Genre()
}

type getAuthorResponse_Fiction struct {
	Fiction bool `protobuf:"varint,2,opt,name=fiction,oneof"`
}

type getAuthorResponse_Nonfiction struct {
	Nonfiction bool `protobuf:"varint,3,opt,name=nonfiction,oneof"`
}

func (*getAuthorResponse_Fiction) isGetAuthorResponse_Genre() {}

func (*getAuthorResponse_Nonfiction) isGetAuthorResponse_Genre() {}

// A shelf resource.
type Shelf struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Theme         *string                `protobuf:"bytes,2,opt,name=theme"`
	xxx_hidden_SearchDecoded *string                `protobuf:"bytes,3,opt,name=search_decoded,json=search[decoded]"`
	xxx_hidden_SearchEncoded *string                `protobuf:"bytes,4,opt,name=search_encoded,json=search%5Bencoded%5D"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Shelf) Reset() {
	*x = Shelf{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shelf) ProtoMessage() {}

func (x *Shelf) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Shelf) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Shelf) GetTheme() string {
	if x != nil {
		if x.xxx_hidden_Theme != nil {
			return *x.xxx_hidden_Theme
		}
		return ""
	}
	return ""
}

func (x *Shelf) GetSearchDecoded() string {
	if x != nil {
		if x.xxx_hidden_SearchDecoded != nil {
			return *x.xxx_hidden_SearchDecoded
		}
		return ""
	}
	return ""
}

func (x *Shelf) GetSearchEncoded() string {
	if x != nil {
		if x.xxx_hidden_SearchEncoded != nil {
			return *x.xxx_hidden_SearchEncoded
		}
		return ""
	}
	return ""
}

func (x *Shelf) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Shelf) SetTheme(v string) {
	x.xxx_hidden_Theme = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Shelf) SetSearchDecoded(v string) {
	x.xxx_hidden_SearchDecoded = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Shelf) SetSearchEncoded(v string) {
	x.xxx_hidden_SearchEncoded = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Shelf) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Shelf) HasTheme() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Shelf) HasSearchDecoded() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Shelf) HasSearchEncoded() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Shelf) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Shelf) ClearTheme() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Theme = nil
}

func (x *Shelf) ClearSearchDecoded() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SearchDecoded = nil
}

func (x *Shelf) ClearSearchEncoded() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_SearchEncoded = nil
}

type Shelf_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A unique shelf id.
	Id *string
	// A theme of the shelf (fiction, poetry, etc).
	Theme *string
	// To test json name is percentage decoded
	SearchDecoded *string
	// To test json name is percentage encoded
	SearchEncoded *string
}

func (b0 Shelf_builder) Build() *Shelf {
	m0 := &Shelf{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	if b.Theme != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Theme = b.Theme
	}
	if b.SearchDecoded != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_SearchDecoded = b.SearchDecoded
	}
	if b.SearchEncoded != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_SearchEncoded = b.SearchEncoded
	}
	return m0
}

// A book genre
type Genre struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Genre) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Genre) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Genre) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Genre) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Genre) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Genre) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Genre) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *Genre) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

type Genre_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A unique genre id.
	Id *int64
	// A genre name.
	Name *string
}

func (b0 Genre_builder) Build() *Genre {
	m0 := &Genre{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

// A book resource.
type Book struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Author      *string                `protobuf:"bytes,2,opt,name=author"`
	xxx_hidden_Title       *string                `protobuf:"bytes,3,opt,name=title"`
	xxx_hidden_Quotes      []string               `protobuf:"bytes,4,rep,name=quotes"`
	xxx_hidden_ShelfId     *string                `protobuf:"bytes,5,opt,name=shelf_id,json=shelfId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Book) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		if x.xxx_hidden_Author != nil {
			return *x.xxx_hidden_Author
		}
		return ""
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *Book) GetQuotes() []string {
	if x != nil {
		return x.xxx_hidden_Quotes
	}
	return nil
}

func (x *Book) GetShelfId() string {
	if x != nil {
		if x.xxx_hidden_ShelfId != nil {
			return *x.xxx_hidden_ShelfId
		}
		return ""
	}
	return ""
}

func (x *Book) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Book) SetAuthor(v string) {
	x.xxx_hidden_Author = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Book) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Book) SetQuotes(v []string) {
	x.xxx_hidden_Quotes = v
}

func (x *Book) SetShelfId(v string) {
	x.xxx_hidden_ShelfId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Book) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Book) HasAuthor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Book) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Book) HasShelfId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Book) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Book) ClearAuthor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Author = nil
}

func (x *Book) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Title = nil
}

func (x *Book) ClearShelfId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ShelfId = nil
}

type Book_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A unique book id.
	Id *string
	// An author of the book.
	Author *string
	// A book title.
	Title *string
	// Quotes from the book.
	Quotes  []string
	ShelfId *string
}

func (b0 Book_builder) Build() *Book {
	m0 := &Book{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Author != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Author = b.Author
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Title = b.Title
	}
	x.xxx_hidden_Quotes = b.Quotes
	if b.ShelfId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_ShelfId = b.ShelfId
	}
	return m0
}

// An author resource.
type Author struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Gender      Author_Gender          `protobuf:"varint,2,opt,name=gender,enum=bookstore.v1.Author_Gender"`
	xxx_hidden_FirstName   *string                `protobuf:"bytes,3,opt,name=first_name,json=firstName"`
	xxx_hidden_LastName    *string                `protobuf:"bytes,4,opt,name=last_name,json=lname"`
	xxx_hidden_Metadata    *string                `protobuf:"bytes,5,opt,name=metadata"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt"`
	xxx_hidden_Books       *[]*anypb.Any          `protobuf:"bytes,7,rep,name=books"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Author) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Author) GetGender() Author_Gender {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Gender
		}
	}
	return Author_GENDER_UNSPECIFIED
}

func (x *Author) GetFirstName() string {
	if x != nil {
		if x.xxx_hidden_FirstName != nil {
			return *x.xxx_hidden_FirstName
		}
		return ""
	}
	return ""
}

func (x *Author) GetLastName() string {
	if x != nil {
		if x.xxx_hidden_LastName != nil {
			return *x.xxx_hidden_LastName
		}
		return ""
	}
	return ""
}

func (x *Author) GetMetadata() string {
	if x != nil {
		if x.xxx_hidden_Metadata != nil {
			return *x.xxx_hidden_Metadata
		}
		return ""
	}
	return ""
}

func (x *Author) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Author) GetBooks() []*anypb.Any {
	if x != nil {
		if x.xxx_hidden_Books != nil {
			return *x.xxx_hidden_Books
		}
	}
	return nil
}

func (x *Author) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *Author) SetGender(v Author_Gender) {
	x.xxx_hidden_Gender = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *Author) SetFirstName(v string) {
	x.xxx_hidden_FirstName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *Author) SetLastName(v string) {
	x.xxx_hidden_LastName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *Author) SetMetadata(v string) {
	x.xxx_hidden_Metadata = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *Author) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Author) SetBooks(v []*anypb.Any) {
	x.xxx_hidden_Books = &v
}

func (x *Author) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Author) HasGender() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Author) HasFirstName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Author) HasLastName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Author) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Author) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Author) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *Author) ClearGender() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Gender = Author_GENDER_UNSPECIFIED
}

func (x *Author) ClearFirstName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_FirstName = nil
}

func (x *Author) ClearLastName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_LastName = nil
}

func (x *Author) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Metadata = nil
}

func (x *Author) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type Author_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A unique author id.
	Id        *int64
	Gender    *Author_Gender
	FirstName *string
	LastName  *string
	Metadata  *string
	CreatedAt *timestamppb.Timestamp
	Books     []*anypb.Any
}

func (b0 Author_builder) Build() *Author {
	m0 := &Author{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Gender != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Gender = *b.Gender
	}
	if b.FirstName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_FirstName = b.FirstName
	}
	if b.LastName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_LastName = b.LastName
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Metadata = b.Metadata
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_Books = &b.Books
	return m0
}

// Response to ListShelves call.
type ListShelvesResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Shelves *[]*Shelf              `protobuf:"bytes,1,rep,name=shelves"`
	xxx_hidden_Mask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=mask"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListShelvesResponse) Reset() {
	*x = ListShelvesResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShelvesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShelvesResponse) ProtoMessage() {}

func (x *ListShelvesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListShelvesResponse) GetShelves() []*Shelf {
	if x != nil {
		if x.xxx_hidden_Shelves != nil {
			return *x.xxx_hidden_Shelves
		}
	}
	return nil
}

func (x *ListShelvesResponse) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.xxx_hidden_Mask
	}
	return nil
}

func (x *ListShelvesResponse) SetShelves(v []*Shelf) {
	x.xxx_hidden_Shelves = &v
}

func (x *ListShelvesResponse) SetMask(v *fieldmaskpb.FieldMask) {
	x.xxx_hidden_Mask = v
}

func (x *ListShelvesResponse) HasMask() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Mask != nil
}

func (x *ListShelvesResponse) ClearMask() {
	x.xxx_hidden_Mask = nil
}

type ListShelvesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Shelves in the bookstore.
	Shelves []*Shelf
	Mask    *fieldmaskpb.FieldMask
}

func (b0 ListShelvesResponse_builder) Build() *ListShelvesResponse {
	m0 := &ListShelvesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Shelves = &b.Shelves
	x.xxx_hidden_Mask = b.Mask
	return m0
}

// Request message for CreateShelf method.
type CreateShelfRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Shelf *Shelf                 `protobuf:"bytes,1,opt,name=shelf"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateShelfRequest) Reset() {
	*x = CreateShelfRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfRequest) ProtoMessage() {}

func (x *CreateShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateShelfRequest) GetShelf() *Shelf {
	if x != nil {
		return x.xxx_hidden_Shelf
	}
	return nil
}

func (x *CreateShelfRequest) SetShelf(v *Shelf) {
	x.xxx_hidden_Shelf = v
}

func (x *CreateShelfRequest) HasShelf() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Shelf != nil
}

func (x *CreateShelfRequest) ClearShelf() {
	x.xxx_hidden_Shelf = nil
}

type CreateShelfRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The shelf resource to create.
	Shelf *Shelf
}

func (b0 CreateShelfRequest_builder) Build() *CreateShelfRequest {
	m0 := &CreateShelfRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Shelf = b.Shelf
	return m0
}

// Request message for GetShelf method.
type GetShelfRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Shelf       *string                `protobuf:"bytes,1,opt,name=shelf"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetShelfRequest) Reset() {
	*x = GetShelfRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfRequest) ProtoMessage() {}

func (x *GetShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetShelfRequest) GetShelf() string {
	if x != nil {
		if x.xxx_hidden_Shelf != nil {
			return *x.xxx_hidden_Shelf
		}
		return ""
	}
	return ""
}

func (x *GetShelfRequest) SetShelf(v string) {
	x.xxx_hidden_Shelf = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetShelfRequest) HasShelf() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetShelfRequest) ClearShelf() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Shelf = nil
}

type GetShelfRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the shelf resource to retrieve.
	Shelf *string
}

func (b0 GetShelfRequest_builder) Build() *GetShelfRequest {
	m0 := &GetShelfRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Shelf != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Shelf = b.Shelf
	}
	return m0
}

// Request message for DeleteShelf method.
type DeleteShelfRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Shelf       *string                `protobuf:"bytes,1,opt,name=shelf"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteShelfRequest) Reset() {
	*x = DeleteShelfRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShelfRequest) ProtoMessage() {}

func (x *DeleteShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteShelfRequest) GetShelf() string {
	if x != nil {
		if x.xxx_hidden_Shelf != nil {
			return *x.xxx_hidden_Shelf
		}
		return ""
	}
	return ""
}

func (x *DeleteShelfRequest) SetShelf(v string) {
	x.xxx_hidden_Shelf = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteShelfRequest) HasShelf() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteShelfRequest) ClearShelf() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Shelf = nil
}

type DeleteShelfRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the shelf to delete.
	Shelf *string
}

func (b0 DeleteShelfRequest_builder) Build() *DeleteShelfRequest {
	m0 := &DeleteShelfRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Shelf != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Shelf = b.Shelf
	}
	return m0
}

// Request message for ListBooks method.
type ListBooksRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Shelf       *string                `protobuf:"bytes,1,opt,name=shelf"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListBooksRequest) GetShelf() string {
	if x != nil {
		if x.xxx_hidden_Shelf != nil {
			return *x.xxx_hidden_Shelf
		}
		return ""
	}
	return ""
}

func (x *ListBooksRequest) SetShelf(v string) {
	x.xxx_hidden_Shelf = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ListBooksRequest) HasShelf() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListBooksRequest) ClearShelf() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Shelf = nil
}

type ListBooksRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ID of the shelf which books to list.
	Shelf *string
}

func (b0 ListBooksRequest_builder) Build() *ListBooksRequest {
	m0 := &ListBooksRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Shelf != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Shelf = b.Shelf
	}
	return m0
}

// Request message for CreateBook method.
type CreateBookRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Shelf       *string                `protobuf:"bytes,1,opt,name=shelf"`
	xxx_hidden_Book        *Book                  `protobuf:"bytes,2,opt,name=book"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateBookRequest) GetShelf() string {
	if x != nil {
		if x.xxx_hidden_Shelf != nil {
			return *x.xxx_hidden_Shelf
		}
		return ""
	}
	return ""
}

func (x *CreateBookRequest) GetBook() *Book {
	if x != nil {
		return x.xxx_hidden_Book
	}
	return nil
}

func (x *CreateBookRequest) SetShelf(v string) {
	x.xxx_hidden_Shelf = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateBookRequest) SetBook(v *Book) {
	x.xxx_hidden_Book = v
}

func (x *CreateBookRequest) HasShelf() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateBookRequest) HasBook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Book != nil
}

func (x *CreateBookRequest) ClearShelf() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Shelf = nil
}

func (x *CreateBookRequest) ClearBook() {
	x.xxx_hidden_Book = nil
}

type CreateBookRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the shelf on which to create a book.
	Shelf *string
	// A book resource to create on the shelf.
	Book *Book
}

func (b0 CreateBookRequest_builder) Build() *CreateBookRequest {
	m0 := &CreateBookRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Shelf != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Shelf = b.Shelf
	}
	x.xxx_hidden_Book = b.Book
	return m0
}

// Request message for GetBook method.
type GetBookRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Shelf         *string                `protobuf:"bytes,1,opt,name=shelf"`
	xxx_hidden_Book          int64                  `protobuf:"varint,2,opt,name=book"`
	xxx_hidden_IncludeAuthor bool                   `protobuf:"varint,3,opt,name=include_author,json=includeAuthor"`
	xxx_hidden_PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize"`
	xxx_hidden_PageToken     *string                `protobuf:"bytes,5,opt,name=page_token,json=pageToken"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBookRequest) GetShelf() string {
	if x != nil {
		if x.xxx_hidden_Shelf != nil {
			return *x.xxx_hidden_Shelf
		}
		return ""
	}
	return ""
}

func (x *GetBookRequest) GetBook() int64 {
	if x != nil {
		return x.xxx_hidden_Book
	}
	return 0
}

func (x *GetBookRequest) GetIncludeAuthor() bool {
	if x != nil {
		return x.xxx_hidden_IncludeAuthor
	}
	return false
}

func (x *GetBookRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *GetBookRequest) GetPageToken() string {
	if x != nil {
		if x.xxx_hidden_PageToken != nil {
			return *x.xxx_hidden_PageToken
		}
		return ""
	}
	return ""
}

func (x *GetBookRequest) SetShelf(v string) {
	x.xxx_hidden_Shelf = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *GetBookRequest) SetBook(v int64) {
	x.xxx_hidden_Book = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *GetBookRequest) SetIncludeAuthor(v bool) {
	x.xxx_hidden_IncludeAuthor = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *GetBookRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *GetBookRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *GetBookRequest) HasShelf() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetBookRequest) HasBook() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetBookRequest) HasIncludeAuthor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetBookRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetBookRequest) HasPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *GetBookRequest) ClearShelf() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Shelf = nil
}

func (x *GetBookRequest) ClearBook() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Book = 0
}

func (x *GetBookRequest) ClearIncludeAuthor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_IncludeAuthor = false
}

func (x *GetBookRequest) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_PageSize = 0
}

func (x *GetBookRequest) ClearPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PageToken = nil
}

type GetBookRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the shelf from which to retrieve a book.
	Shelf *string
	// The ID of the book to retrieve.
	Book          *int64
	IncludeAuthor *bool
	PageSize      *int32
	PageToken     *string
}

func (b0 GetBookRequest_builder) Build() *GetBookRequest {
	m0 := &GetBookRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Shelf != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Shelf = b.Shelf
	}
	if b.Book != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Book = *b.Book
	}
	if b.IncludeAuthor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_IncludeAuthor = *b.IncludeAuthor
	}
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_PageToken = b.PageToken
	}
	return m0
}

// Request message for UpdateBook method
type UpdateBookRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Shelf       *string                `protobuf:"bytes,1,opt,name=shelf"`
	xxx_hidden_Book        *Book                  `protobuf:"bytes,2,opt,name=book"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateBookRequest) GetShelf() string {
	if x != nil {
		if x.xxx_hidden_Shelf != nil {
			return *x.xxx_hidden_Shelf
		}
		return ""
	}
	return ""
}

func (x *UpdateBookRequest) GetBook() *Book {
	if x != nil {
		return x.xxx_hidden_Book
	}
	return nil
}

func (x *UpdateBookRequest) SetShelf(v string) {
	x.xxx_hidden_Shelf = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UpdateBookRequest) SetBook(v *Book) {
	x.xxx_hidden_Book = v
}

func (x *UpdateBookRequest) HasShelf() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateBookRequest) HasBook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Book != nil
}

func (x *UpdateBookRequest) ClearShelf() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Shelf = nil
}

func (x *UpdateBookRequest) ClearBook() {
	x.xxx_hidden_Book = nil
}

type UpdateBookRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the shelf from which to retrieve a book.
	Shelf *string
	// A book resource to update on the shelf.
	Book *Book
}

func (b0 UpdateBookRequest_builder) Build() *UpdateBookRequest {
	m0 := &UpdateBookRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Shelf != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Shelf = b.Shelf
	}
	x.xxx_hidden_Book = b.Book
	return m0
}

// Request message for DeleteBook method.
type DeleteBookRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Book *Book                  `protobuf:"bytes,1,opt,name=book"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteBookRequest) GetBook() *Book {
	if x != nil {
		return x.xxx_hidden_Book
	}
	return nil
}

func (x *DeleteBookRequest) SetBook(v *Book) {
	x.xxx_hidden_Book = v
}

func (x *DeleteBookRequest) HasBook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Book != nil
}

func (x *DeleteBookRequest) ClearBook() {
	x.xxx_hidden_Book = nil
}

type DeleteBookRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The book resource to delete.
	Book *Book
}

func (b0 DeleteBookRequest_builder) Build() *DeleteBookRequest {
	m0 := &DeleteBookRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Book = b.Book
	return m0
}

// Request message for GetAuthor method.
type GetAuthorRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Author      int64                  `protobuf:"varint,1,opt,name=author"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAuthorRequest) GetAuthor() int64 {
	if x != nil {
		return x.xxx_hidden_Author
	}
	return 0
}

func (x *GetAuthorRequest) SetAuthor(v int64) {
	x.xxx_hidden_Author = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetAuthorRequest) HasAuthor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetAuthorRequest) ClearAuthor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Author = 0
}

type GetAuthorRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the author resource to retrieve.
	Author *int64
}

func (b0 GetAuthorRequest_builder) Build() *GetAuthorRequest {
	m0 := &GetAuthorRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Author != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Author = *b.Author
	}
	return m0
}

// A recursive comment for the recursive request
type RecursiveBookRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BookId      *string                `protobuf:"bytes,1,opt,name=book_id,json=bookId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RecursiveBookRequest) Reset() {
	*x = RecursiveBookRequest{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveBookRequest) ProtoMessage() {}

func (x *RecursiveBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecursiveBookRequest) GetBookId() string {
	if x != nil {
		if x.xxx_hidden_BookId != nil {
			return *x.xxx_hidden_BookId
		}
		return ""
	}
	return ""
}

func (x *RecursiveBookRequest) SetBookId(v string) {
	x.xxx_hidden_BookId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RecursiveBookRequest) HasBookId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RecursiveBookRequest) ClearBookId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BookId = nil
}

type RecursiveBookRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A book ID!
	BookId *string
}

func (b0 RecursiveBookRequest_builder) Build() *RecursiveBookRequest {
	m0 := &RecursiveBookRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BookId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_BookId = b.BookId
	}
	return m0
}

// A recursive comment for the recursive response
type RecursiveBookResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Page        *RecursivePage         `protobuf:"bytes,1,opt,name=page"`
	xxx_hidden_AnotherProp *string                `protobuf:"bytes,2,opt,name=another_prop,json=anotherProp"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RecursiveBookResponse) Reset() {
	*x = RecursiveBookResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveBookResponse) ProtoMessage() {}

func (x *RecursiveBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecursiveBookResponse) GetPage() *RecursivePage {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return nil
}

func (x *RecursiveBookResponse) GetAnotherProp() string {
	if x != nil {
		if x.xxx_hidden_AnotherProp != nil {
			return *x.xxx_hidden_AnotherProp
		}
		return ""
	}
	return ""
}

func (x *RecursiveBookResponse) SetPage(v *RecursivePage) {
	x.xxx_hidden_Page = v
}

func (x *RecursiveBookResponse) SetAnotherProp(v string) {
	x.xxx_hidden_AnotherProp = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RecursiveBookResponse) HasPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Page != nil
}

func (x *RecursiveBookResponse) HasAnotherProp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RecursiveBookResponse) ClearPage() {
	x.xxx_hidden_Page = nil
}

func (x *RecursiveBookResponse) ClearAnotherProp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AnotherProp = nil
}

type RecursiveBookResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// This is a recursive page
	Page *RecursivePage
	// This is a non recursive secondary prop
	AnotherProp *string
}

func (b0 RecursiveBookResponse_builder) Build() *RecursiveBookResponse {
	m0 := &RecursiveBookResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Page = b.Page
	if b.AnotherProp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AnotherProp = b.AnotherProp
	}
	return m0
}

// A recursive page for the recursive response
type RecursivePage struct {
	state                  protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Books       *RecursiveBookResponse    `protobuf:"bytes,1,opt,name=books"`
	xxx_hidden_Pages       *[]*RecursiveBookResponse `protobuf:"bytes,2,rep,name=pages"`
	xxx_hidden_ExtraPages  *[]*RecursivePage         `protobuf:"bytes,3,rep,name=extra_pages,json=extraPages"`
	xxx_hidden_Prop        *string                   `protobuf:"bytes,4,opt,name=prop"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RecursivePage) Reset() {
	*x = RecursivePage{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursivePage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursivePage) ProtoMessage() {}

func (x *RecursivePage) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecursivePage) GetBooks() *RecursiveBookResponse {
	if x != nil {
		return x.xxx_hidden_Books
	}
	return nil
}

func (x *RecursivePage) GetPages() []*RecursiveBookResponse {
	if x != nil {
		if x.xxx_hidden_Pages != nil {
			return *x.xxx_hidden_Pages
		}
	}
	return nil
}

func (x *RecursivePage) GetExtraPages() []*RecursivePage {
	if x != nil {
		if x.xxx_hidden_ExtraPages != nil {
			return *x.xxx_hidden_ExtraPages
		}
	}
	return nil
}

func (x *RecursivePage) GetProp() string {
	if x != nil {
		if x.xxx_hidden_Prop != nil {
			return *x.xxx_hidden_Prop
		}
		return ""
	}
	return ""
}

func (x *RecursivePage) SetBooks(v *RecursiveBookResponse) {
	x.xxx_hidden_Books = v
}

func (x *RecursivePage) SetPages(v []*RecursiveBookResponse) {
	x.xxx_hidden_Pages = &v
}

func (x *RecursivePage) SetExtraPages(v []*RecursivePage) {
	x.xxx_hidden_ExtraPages = &v
}

func (x *RecursivePage) SetProp(v string) {
	x.xxx_hidden_Prop = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *RecursivePage) HasBooks() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Books != nil
}

func (x *RecursivePage) HasProp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RecursivePage) ClearBooks() {
	x.xxx_hidden_Books = nil
}

func (x *RecursivePage) ClearProp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Prop = nil
}

type RecursivePage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// This is a recursive book
	Books *RecursiveBookResponse
	// This is a list of recursive books
	Pages []*RecursiveBookResponse
	// This is a list of recursive pages
	ExtraPages []*RecursivePage
	// This is a non recursive prop
	Prop *string
}

func (b0 RecursivePage_builder) Build() *RecursivePage {
	m0 := &RecursivePage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Books = b.Books
	x.xxx_hidden_Pages = &b.Pages
	x.xxx_hidden_ExtraPages = &b.ExtraPages
	if b.Prop != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Prop = b.Prop
	}
	return m0
}

type ListBooksResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Books *[]*Book               `protobuf:"bytes,1,rep,name=books"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_v1_bookstore_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListBooksResponse) GetBooks() []*Book {
	if x != nil {
		if x.xxx_hidden_Books != nil {
			return *x.xxx_hidden_Books
		}
	}
	return nil
}

func (x *ListBooksResponse) SetBooks(v []*Book) {
	x.xxx_hidden_Books = &v
}

type ListBooksResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Books []*Book
}

func (b0 ListBooksResponse_builder) Build() *ListBooksResponse {
	m0 := &ListBooksResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Books = &b.Books
	return m0
}

var File_bookstore_v1_bookstore_proto protoreflect.FileDescriptor

const file_bookstore_v1_bookstore_proto_rawDesc = "" +
	"\n" +
	"\x1cbookstore/v1/bookstore.proto\x12\fbookstore.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19google/protobuf/any.proto\x1a google/protobuf/field_mask.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14mcpgw/v1/mcpgw.proto\"N\n" +
	"\x12CreateGenreRequest\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xbaH\x06r\x04\x10\x01\x182\xe2\x9c\x04\x17\n" +
	"\x15The name of the genreR\x04name\"@\n" +
	"\x13CreateGenreResponse\x12)\n" +
	"\x05genre\x18\x01 \x01(\v2\x13.bookstore.v1.GenreR\x05genre\",\n" +
	"\x0fGetGenreRequest\x12\x19\n" +
	"\bgenre_id\x18\x01 \x01(\tR\agenreId\"=\n" +
	"\x10GetGenreResponse\x12)\n" +
	"\x05genre\x18\x01 \x01(\v2\x13.bookstore.v1.GenreR\x05genre\"/\n" +
	"\x12DeleteGenreRequest\x12\x19\n" +
	"\bgenre_id\x18\x01 \x01(\tR\agenreId\"\x15\n" +
	"\x13DeleteGenreResponse\"\x13\n" +
	"\x11ListGenresRequest\"A\n" +
	"\x12ListGenresResponse\x12+\n" +
	"\x06genres\x18\x01 \x03(\v2\x13.bookstore.v1.GenreR\x06genres\"\x15\n" +
	"\x13DeleteShelfResponse\"\x14\n" +
	"\x12ListShelvesRequest\"\x14\n" +
	"\x12DeleteBookResponse\"@\n" +
	"\x13CreateShelfResponse\x12)\n" +
	"\x05shelf\x18\x01 \x01(\v2\x13.bookstore.v1.ShelfR\x05shelf\"<\n" +
	"\x12CreateBookResponse\x12&\n" +
	"\x04book\x18\x01 \x01(\v2\x12.bookstore.v1.BookR\x04book\"9\n" +
	"\x0fGetBookResponse\x12&\n" +
	"\x04book\x18\x01 \x01(\v2\x12.bookstore.v1.BookR\x04book\"<\n" +
	"\x12UpdateBookResponse\x12&\n" +
	"\x04book\x18\x01 \x01(\v2\x12.bookstore.v1.BookR\x04book\"\x88\x01\n" +
	"\x11GetAuthorResponse\x12,\n" +
	"\x06author\x18\x01 \x01(\v2\x14.bookstore.v1.AuthorR\x06author\x12\x1a\n" +
	"\afiction\x18\x02 \x01(\bH\x00R\afiction\x12 \n" +
	"\n" +
	"nonfiction\x18\x03 \x01(\bH\x00R\n" +
	"nonfictionB\a\n" +
	"\x05genre\"\x83\x01\n" +
	"\x05Shelf\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme\x12'\n" +
	"\x0esearch_decoded\x18\x03 \x01(\tR\x0fsearch[decoded]\x12+\n" +
	"\x0esearch_encoded\x18\x04 \x01(\tR\x13search%5Bencoded%5D\"+\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"w\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06quotes\x18\x04 \x03(\tR\x06quotes\x12\x19\n" +
	"\bshelf_id\x18\x05 \x01(\tR\ashelfId\"\xcf\x02\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x123\n" +
	"\x06gender\x18\x02 \x01(\x0e2\x1b.bookstore.v1.Author.GenderR\x06gender\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x18\n" +
	"\tlast_name\x18\x04 \x01(\tR\x05lname\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12*\n" +
	"\x05books\x18\a \x03(\v2\x14.google.protobuf.AnyR\x05books\"D\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02\"t\n" +
	"\x13ListShelvesResponse\x12-\n" +
	"\ashelves\x18\x01 \x03(\v2\x13.bookstore.v1.ShelfR\ashelves\x12.\n" +
	"\x04mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"?\n" +
	"\x12CreateShelfRequest\x12)\n" +
	"\x05shelf\x18\x01 \x01(\v2\x13.bookstore.v1.ShelfR\x05shelf\"'\n" +
	"\x0fGetShelfRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\tR\x05shelf\"*\n" +
	"\x12DeleteShelfRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\tR\x05shelf\"(\n" +
	"\x10ListBooksRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\tR\x05shelf\"Q\n" +
	"\x11CreateBookRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\tR\x05shelf\x12&\n" +
	"\x04book\x18\x02 \x01(\v2\x12.bookstore.v1.BookR\x04book\"\x9d\x01\n" +
	"\x0eGetBookRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\tR\x05shelf\x12\x12\n" +
	"\x04book\x18\x02 \x01(\x03R\x04book\x12%\n" +
	"\x0einclude_author\x18\x03 \x01(\bR\rincludeAuthor\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"Q\n" +
	"\x11UpdateBookRequest\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\tR\x05shelf\x12&\n" +
	"\x04book\x18\x02 \x01(\v2\x12.bookstore.v1.BookR\x04book\";\n" +
	"\x11DeleteBookRequest\x12&\n" +
	"\x04book\x18\x01 \x01(\v2\x12.bookstore.v1.BookR\x04book\"*\n" +
	"\x10GetAuthorRequest\x12\x16\n" +
	"\x06author\x18\x01 \x01(\x03R\x06author\"/\n" +
	"\x14RecursiveBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"k\n" +
	"\x15RecursiveBookResponse\x12/\n" +
	"\x04page\x18\x01 \x01(\v2\x1b.bookstore.v1.RecursivePageR\x04page\x12!\n" +
	"\fanother_prop\x18\x02 \x01(\tR\vanotherProp\"\xd7\x01\n" +
	"\rRecursivePage\x129\n" +
	"\x05books\x18\x01 \x01(\v2#.bookstore.v1.RecursiveBookResponseR\x05books\x129\n" +
	"\x05pages\x18\x02 \x03(\v2#.bookstore.v1.RecursiveBookResponseR\x05pages\x12<\n" +
	"\vextra_pages\x18\x03 \x03(\v2\x1b.bookstore.v1.RecursivePageR\n" +
	"extraPages\x12\x12\n" +
	"\x04prop\x18\x04 \x01(\tR\x04prop\"=\n" +
	"\x11ListBooksResponse\x12(\n" +
	"\x05books\x18\x01 \x03(\v2\x12.bookstore.v1.BookR\x05books2\x95\x0e\n" +
	"\x10BookstoreService\x12\x9b\x01\n" +
	"\vListShelves\x12 .bookstore.v1.ListShelvesRequest\x1a!.bookstore.v1.ListShelvesResponse\"Gڜ\x04C\n" +
	"\fList Shelves\x12!List all shelves in the bookstore\x18\x01(\x01:\flist_shelves\x12\x99\x01\n" +
	"\vCreateShelf\x12 .bookstore.v1.CreateShelfRequest\x1a!.bookstore.v1.CreateShelfResponse\"Eڜ\x04A\n" +
	"\fCreate Shelf\x12#Create a new shelf in the bookstore:\fcreate_shelf\x12\x97\x01\n" +
	"\vDeleteShelf\x12 .bookstore.v1.DeleteShelfRequest\x1a!.bookstore.v1.DeleteShelfResponse\"Cڜ\x04?\n" +
	"\fDelete Shelf\x12\x1fDelete a shelf in the bookstore \x01:\fdelete_shelf\x12\x93\x01\n" +
	"\n" +
	"ListGenres\x12\x1f.bookstore.v1.ListGenresRequest\x1a .bookstore.v1.ListGenresResponse\"Bڜ\x04>\n" +
	"\vList Genres\x12 List all genres in the bookstore\x18\x01:\vlist_genres\x12\x99\x01\n" +
	"\vCreateGenre\x12 .bookstore.v1.CreateGenreRequest\x1a!.bookstore.v1.CreateGenreResponse\"Eڜ\x04A\n" +
	"\fCreate Genre\x12#Create a new genre in the bookstore:\fcreate_genre\x12\x83\x01\n" +
	"\bGetGenre\x12\x1d.bookstore.v1.GetGenreRequest\x1a\x1e.bookstore.v1.GetGenreResponse\"8ڜ\x044\n" +
	"\tGet Genre\x12\x1cGet a genre in the bookstore:\tget_genre\x12\x97\x01\n" +
	"\vDeleteGenre\x12 .bookstore.v1.DeleteGenreRequest\x1a!.bookstore.v1.DeleteGenreResponse\"Cڜ\x04?\n" +
	"\fDelete Genre\x12\x1fDelete a genre in the bookstore \x01:\fdelete_genre\x12\x99\x01\n" +
	"\n" +
	"CreateBook\x12\x1f.bookstore.v1.CreateBookRequest\x1a .bookstore.v1.CreateBookResponse\"Hڜ\x04D\n" +
	"\vCreate Book\x12\"Create a new book in the bookstore \x01(\x010\x01:\vcreate_book\x12\x83\x01\n" +
	"\aGetBook\x12\x1c.bookstore.v1.GetBookRequest\x1a\x1d.bookstore.v1.GetBookResponse\";ڜ\x047\n" +
	"\bGet Book\x12\x1bGet a book in the bookstore\x18\x01(\x010\x01:\bget_book\x12\x91\x01\n" +
	"\tListBooks\x12\x1e.bookstore.v1.ListBooksRequest\x1a\x1f.bookstore.v1.ListBooksResponse\"Cڜ\x04?\n" +
	"\n" +
	"List Books\x12\x1fList all books in the bookstore\x18\x01(\x010\x01:\n" +
	"list_books\x12\x91\x01\n" +
	"\n" +
	"DeleteBook\x12\x1f.bookstore.v1.DeleteBookRequest\x1a .bookstore.v1.DeleteBookResponse\"@ڜ\x04<\n" +
	"\vDelete Book\x12\x1eDelete a book in the bookstore \x01:\vdelete_book\x12\x88\x01\n" +
	"\n" +
	"UpdateBook\x12\x1f.bookstore.v1.UpdateBookRequest\x1a .bookstore.v1.UpdateBookResponse\"7ڜ\x043\n" +
	"\vUpdate Book\x12\x1eUpdate a book in the bookstore \x01(\x010\x01\x1a\x06Ҝ\x04\x02\b\x01B\xb5\x01\n" +
	"\x10com.bookstore.v1B\x0eBookstoreProtoP\x01Z8github.com/ductone/protoc-gen-mcpgw/example/bookstore/v1\xa2\x02\x03BXX\xaa\x02\fBookstore.V1\xca\x02\fBookstore\\V1\xe2\x02\x18Bookstore\\V1\\GPBMetadata\xea\x02\rBookstore::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_bookstore_v1_bookstore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bookstore_v1_bookstore_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_bookstore_v1_bookstore_proto_goTypes = []any{
	(Author_Gender)(0),            // 0: bookstore.v1.Author.Gender
	(*CreateGenreRequest)(nil),    // 1: bookstore.v1.CreateGenreRequest
	(*CreateGenreResponse)(nil),   // 2: bookstore.v1.CreateGenreResponse
	(*GetGenreRequest)(nil),       // 3: bookstore.v1.GetGenreRequest
	(*GetGenreResponse)(nil),      // 4: bookstore.v1.GetGenreResponse
	(*DeleteGenreRequest)(nil),    // 5: bookstore.v1.DeleteGenreRequest
	(*DeleteGenreResponse)(nil),   // 6: bookstore.v1.DeleteGenreResponse
	(*ListGenresRequest)(nil),     // 7: bookstore.v1.ListGenresRequest
	(*ListGenresResponse)(nil),    // 8: bookstore.v1.ListGenresResponse
	(*DeleteShelfResponse)(nil),   // 9: bookstore.v1.DeleteShelfResponse
	(*ListShelvesRequest)(nil),    // 10: bookstore.v1.ListShelvesRequest
	(*DeleteBookResponse)(nil),    // 11: bookstore.v1.DeleteBookResponse
	(*CreateShelfResponse)(nil),   // 12: bookstore.v1.CreateShelfResponse
	(*CreateBookResponse)(nil),    // 13: bookstore.v1.CreateBookResponse
	(*GetBookResponse)(nil),       // 14: bookstore.v1.GetBookResponse
	(*UpdateBookResponse)(nil),    // 15: bookstore.v1.UpdateBookResponse
	(*GetAuthorResponse)(nil),     // 16: bookstore.v1.GetAuthorResponse
	(*Shelf)(nil),                 // 17: bookstore.v1.Shelf
	(*Genre)(nil),                 // 18: bookstore.v1.Genre
	(*Book)(nil),                  // 19: bookstore.v1.Book
	(*Author)(nil),                // 20: bookstore.v1.Author
	(*ListShelvesResponse)(nil),   // 21: bookstore.v1.ListShelvesResponse
	(*CreateShelfRequest)(nil),    // 22: bookstore.v1.CreateShelfRequest
	(*GetShelfRequest)(nil),       // 23: bookstore.v1.GetShelfRequest
	(*DeleteShelfRequest)(nil),    // 24: bookstore.v1.DeleteShelfRequest
	(*ListBooksRequest)(nil),      // 25: bookstore.v1.ListBooksRequest
	(*CreateBookRequest)(nil),     // 26: bookstore.v1.CreateBookRequest
	(*GetBookRequest)(nil),        // 27: bookstore.v1.GetBookRequest
	(*UpdateBookRequest)(nil),     // 28: bookstore.v1.UpdateBookRequest
	(*DeleteBookRequest)(nil),     // 29: bookstore.v1.DeleteBookRequest
	(*GetAuthorRequest)(nil),      // 30: bookstore.v1.GetAuthorRequest
	(*RecursiveBookRequest)(nil),  // 31: bookstore.v1.RecursiveBookRequest
	(*RecursiveBookResponse)(nil), // 32: bookstore.v1.RecursiveBookResponse
	(*RecursivePage)(nil),         // 33: bookstore.v1.RecursivePage
	(*ListBooksResponse)(nil),     // 34: bookstore.v1.ListBooksResponse
	(*timestamppb.Timestamp)(nil), // 35: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 36: google.protobuf.Any
	(*fieldmaskpb.FieldMask)(nil), // 37: google.protobuf.FieldMask
}
var file_bookstore_v1_bookstore_proto_depIdxs = []int32{
	18, // 0: bookstore.v1.CreateGenreResponse.genre:type_name -> bookstore.v1.Genre
	18, // 1: bookstore.v1.GetGenreResponse.genre:type_name -> bookstore.v1.Genre
	18, // 2: bookstore.v1.ListGenresResponse.genres:type_name -> bookstore.v1.Genre
	17, // 3: bookstore.v1.CreateShelfResponse.shelf:type_name -> bookstore.v1.Shelf
	19, // 4: bookstore.v1.CreateBookResponse.book:type_name -> bookstore.v1.Book
	19, // 5: bookstore.v1.GetBookResponse.book:type_name -> bookstore.v1.Book
	19, // 6: bookstore.v1.UpdateBookResponse.book:type_name -> bookstore.v1.Book
	20, // 7: bookstore.v1.GetAuthorResponse.author:type_name -> bookstore.v1.Author
	0,  // 8: bookstore.v1.Author.gender:type_name -> bookstore.v1.Author.Gender
	35, // 9: bookstore.v1.Author.created_at:type_name -> google.protobuf.Timestamp
	36, // 10: bookstore.v1.Author.books:type_name -> google.protobuf.Any
	17, // 11: bookstore.v1.ListShelvesResponse.shelves:type_name -> bookstore.v1.Shelf
	37, // 12: bookstore.v1.ListShelvesResponse.mask:type_name -> google.protobuf.FieldMask
	17, // 13: bookstore.v1.CreateShelfRequest.shelf:type_name -> bookstore.v1.Shelf
	19, // 14: bookstore.v1.CreateBookRequest.book:type_name -> bookstore.v1.Book
	19, // 15: bookstore.v1.UpdateBookRequest.book:type_name -> bookstore.v1.Book
	19, // 16: bookstore.v1.DeleteBookRequest.book:type_name -> bookstore.v1.Book
	33, // 17: bookstore.v1.RecursiveBookResponse.page:type_name -> bookstore.v1.RecursivePage
	32, // 18: bookstore.v1.RecursivePage.books:type_name -> bookstore.v1.RecursiveBookResponse
	32, // 19: bookstore.v1.RecursivePage.pages:type_name -> bookstore.v1.RecursiveBookResponse
	33, // 20: bookstore.v1.RecursivePage.extra_pages:type_name -> bookstore.v1.RecursivePage
	19, // 21: bookstore.v1.ListBooksResponse.books:type_name -> bookstore.v1.Book
	10, // 22: bookstore.v1.BookstoreService.ListShelves:input_type -> bookstore.v1.ListShelvesRequest
	22, // 23: bookstore.v1.BookstoreService.CreateShelf:input_type -> bookstore.v1.CreateShelfRequest
	24, // 24: bookstore.v1.BookstoreService.DeleteShelf:input_type -> bookstore.v1.DeleteShelfRequest
	7,  // 25: bookstore.v1.BookstoreService.ListGenres:input_type -> bookstore.v1.ListGenresRequest
	1,  // 26: bookstore.v1.BookstoreService.CreateGenre:input_type -> bookstore.v1.CreateGenreRequest
	3,  // 27: bookstore.v1.BookstoreService.GetGenre:input_type -> bookstore.v1.GetGenreRequest
	5,  // 28: bookstore.v1.BookstoreService.DeleteGenre:input_type -> bookstore.v1.DeleteGenreRequest
	26, // 29: bookstore.v1.BookstoreService.CreateBook:input_type -> bookstore.v1.CreateBookRequest
	27, // 30: bookstore.v1.BookstoreService.GetBook:input_type -> bookstore.v1.GetBookRequest
	25, // 31: bookstore.v1.BookstoreService.ListBooks:input_type -> bookstore.v1.ListBooksRequest
	29, // 32: bookstore.v1.BookstoreService.DeleteBook:input_type -> bookstore.v1.DeleteBookRequest
	28, // 33: bookstore.v1.BookstoreService.UpdateBook:input_type -> bookstore.v1.UpdateBookRequest
	21, // 34: bookstore.v1.BookstoreService.ListShelves:output_type -> bookstore.v1.ListShelvesResponse
	12, // 35: bookstore.v1.BookstoreService.CreateShelf:output_type -> bookstore.v1.CreateShelfResponse
	9,  // 36: bookstore.v1.BookstoreService.DeleteShelf:output_type -> bookstore.v1.DeleteShelfResponse
	8,  // 37: bookstore.v1.BookstoreService.ListGenres:output_type -> bookstore.v1.ListGenresResponse
	2,  // 38: bookstore.v1.BookstoreService.CreateGenre:output_type -> bookstore.v1.CreateGenreResponse
	4,  // 39: bookstore.v1.BookstoreService.GetGenre:output_type -> bookstore.v1.GetGenreResponse
	6,  // 40: bookstore.v1.BookstoreService.DeleteGenre:output_type -> bookstore.v1.DeleteGenreResponse
	13, // 41: bookstore.v1.BookstoreService.CreateBook:output_type -> bookstore.v1.CreateBookResponse
	14, // 42: bookstore.v1.BookstoreService.GetBook:output_type -> bookstore.v1.GetBookResponse
	34, // 43: bookstore.v1.BookstoreService.ListBooks:output_type -> bookstore.v1.ListBooksResponse
	11, // 44: bookstore.v1.BookstoreService.DeleteBook:output_type -> bookstore.v1.DeleteBookResponse
	15, // 45: bookstore.v1.BookstoreService.UpdateBook:output_type -> bookstore.v1.UpdateBookResponse
	34, // [34:46] is the sub-list for method output_type
	22, // [22:34] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_bookstore_v1_bookstore_proto_init() }
func file_bookstore_v1_bookstore_proto_init() {
	if File_bookstore_v1_bookstore_proto != nil {
		return
	}
	file_bookstore_v1_bookstore_proto_msgTypes[15].OneofWrappers = []any{
		(*getAuthorResponse_Fiction)(nil),
		(*getAuthorResponse_Nonfiction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bookstore_v1_bookstore_proto_rawDesc), len(file_bookstore_v1_bookstore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookstore_v1_bookstore_proto_goTypes,
		DependencyIndexes: file_bookstore_v1_bookstore_proto_depIdxs,
		EnumInfos:         file_bookstore_v1_bookstore_proto_enumTypes,
		MessageInfos:      file_bookstore_v1_bookstore_proto_msgTypes,
	}.Build()
	File_bookstore_v1_bookstore_proto = out.File
	file_bookstore_v1_bookstore_proto_goTypes = nil
	file_bookstore_v1_bookstore_proto_depIdxs = nil
}
